server:
  port: 8080

spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

tmdb:
  base-url: https://api.themoviedb.org/3
  connect-timeout-ms: 3000
  read-timeout-ms: 5000

app:
  cache:
    movie-search:
      ttl-minutes: 10
      max-size: 500
